### PR TITLE
add challengeResults to dump file and specs

### LINKED ISSUE #14: Add participation and submission levels to JSON dump

### LINKED ISSUE #19: Adding a challenge is failing due to EmbeddedDocument
The latest `Challenge` schema has a property that is an EmbeddedDocument. Now, creating a new challenge is met with the following error:

```
HTTP response body: {
  "detail": "The source SON object needs to be of type 'dict' but a '<class 'openapi_server.models.challenge_results.ChallengeResults'>' was found",
  "status": 500,
  "title": "Internal error"
}
```

Attempted fixes:

**1/** convert the value to a `ChallengeResults` object
```
results = challenge.get("challengeResults")
challenge["challengeResults"] = roccclient.ChallengeResults(
    n_submissions=results.get("nSubmissions"),
    n_registered_participants=results.get("nParticipants")
)
api.create_challenge(challenge=challenge)
```
**2/** convert the value to a dict-form of the `ChallengeResults` object
```
results = challenge.get("challengeResults")
challenge["challengeResults"] = roccclient.ChallengeResults(
    n_submissions=results.get("nSubmissions"),
    n_registered_participants=results.get("nParticipants")
).to_dict()
api.create_challenge(challenge=challenge)
```
**3/** testing with an empty dict
```
challenge["challengeResults"] = {}
api.create_challenge(challenge=challenge)
```
**4/** testing with an empty list (this results in a `400` status code)
```
challenge["challengeResults"] = []
api.create_challenge(challenge=challenge)
```

**Temporary fix:** just remove the value altogether
```
del challenge["challengeResults"]
api.create_challenge(challenge=challenge)
```

### LINKED ISSUE #20: Add exception handling for when adding a challenge fails due to a 500 error
_Originally posted by @tschaffter in https://github.com/Sage-Bionetworks/rocc-client/pull/18#issuecomment-748147833_

### PR DESCRIPTION
**Pull request by vpchung**
With this PR:
* add challenge results to JSON dump
* update specs to reflect changes in schemas, e.g. `challengeResults.nSubmissions`
* JSON dump had some redundant `persons` entries, e.g. "Mike Mason" and "Michael Mason"

### CODE REVIEW

**Comment by vpchung** [comment]
TODO:
* adding a challenge is now met with the following error:

```
HTTP response body: {
  "detail": "The source SON object needs to be of type 'dict' but a '<class 'openapi_server.models.challenge_results.ChallengeResults'>' was found",
  "status": 500,
  "title": "Internal error"
}
```

Still not sure where the fix needs to be: schemas? dbmodels?

**Comment by tschaffter** [comment]
One potential issue is that the schema has the property `ChallengeResults.nRegisteredParticipants` but the JSON dump has `ChallengeResults.nParticipants`. I think that the name defined in the schema is more descriptive. We can ultimately have `nParticipants` to track the number of participants who have actually "participated", i.e. are linked to at least one valid submission.

**Comment by tschaffter** [comment]
@vpchung I confirm that I can reproduce the issue.

**Comment by tschaffter** [comment]
TODO:

- [ ] The push script should exit when one challenge failed to be pushed

**Comment by tschaffter** [comment]
@vpchung I'm moving ahead and merging this PR to make it easier for me to work on the notebook.

**Comment by tschaffter** [comment]
I forgot to remove the line that deleted challenge results in the push script. This is now fixed in the branch `develop`.

**Pull request merged**
